// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_hSlEw0HBczjw7df9hPRuLFb91gjPteY',
    appId: '1:640983208425:web:3608113aeab998719ebb78',
    messagingSenderId: '640983208425',
    projectId: 'aims-5d185',
    authDomain: 'aims-5d185.firebaseapp.com',
    storageBucket: 'aims-5d185.firebasestorage.app',
    measurementId: 'G-VCYQD3G29S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpbse4pWIhGKQzrrs8x_sG4_hnhIerEog',
    appId: '1:640983208425:android:41154c8efb66d9229ebb78',
    messagingSenderId: '640983208425',
    projectId: 'aims-5d185',
    storageBucket: 'aims-5d185.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClgMZlT-io7P4I2C2EckoZ1HVbZDVn3MQ',
    appId: '1:640983208425:ios:3b42fe2f79838e5c9ebb78',
    messagingSenderId: '640983208425',
    projectId: 'aims-5d185',
    storageBucket: 'aims-5d185.firebasestorage.app',
    iosBundleId: 'com.leosgroup.aims.admin.aimsAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClgMZlT-io7P4I2C2EckoZ1HVbZDVn3MQ',
    appId: '1:640983208425:ios:3b42fe2f79838e5c9ebb78',
    messagingSenderId: '640983208425',
    projectId: 'aims-5d185',
    storageBucket: 'aims-5d185.firebasestorage.app',
    iosBundleId: 'com.leosgroup.aims.admin.aimsAdmin',
  );
}
